### ISSUE TITLE
experimental/optional is not detected and used even if present

### ISSUE THREAD

**Issue by ilyapopov** [AMDmi3/libSDL2pp#33]
This happens for both gcc/libstdc++ and clang++/libc++, because `experimental/optional` is only in C++14 standard and not in C++11, and both `gcc` and `clang` refuse to compile the test program with `-std=c++11` flag.

Tested on Ubuntu 14.10 with gcc 4.9.1 and clang 3.5.0.

And the same with `[[deprecated]]`.

I see two solutions:
- Use `-std=c++14` flag when possible. 
- Since optional is bundled anyway always use the bundled version.

**Comment by AMDmi3** [comment]
This works as intended - if compiler refuses to compile test program, it won't be able to use experimental/optional.

**Comment by ilyapopov** [comment]
As the check is written now it is useless. Any conforming compiler will refuse it in C++11 mode, even if the header is present and can be actually used in C++14 mode.

**Comment by AMDmi3** [comment]
The logic is pretty simple: if the header may be used (which is checked), it is used, otherwise it is not. Yes, in C++14 mode the check succeeds and the header is used - that's on which it is primarily targeted.

**Comment by ilyapopov** [comment]
Ok, I see now. So, to be able to use these features, I shall manually set `SDL2PP_CXXSTD` to `c++14`. 
I believe the issue can

**Comment by AMDmi3** [comment]
> Use ```-std=c++14``` flag when possible

It'd be unwise to tighten standard requirements for non-critical features. The library is designed in a way that it works with c++11, but takes benefit of c++14 features if they are available. Yes, that's what SDL2PP_CXXSTD is for, however I also would not bet on compiler's strict standard conformance in a way that some c++14 features would not be available even in c++11 mode.
For instance, ```[[deprecated]]``` does work on my FreeBSD box with clang 3.5 + libc++ even with -std=c++11.

> Since optional is bundled anyway always use the bundled version

I'd prefer to stick to c++ library's header if possible - it may have (or acquire in future) improvements over bundled version, it should be more compatible to the rest of c++ library and it can be expected to be closer to what is hopefully going to be included into c++1z as std::optional.

> I believe the issue can be closed now

Okay, thanks for your interest anyway!
